import React, { useEffect, useMemo, useRef, useState } from 'react';
import { keepPreviousData, useQuery } from '@tanstack/react-query';
import { useSearchParams } from 'react-router-dom';
import { RefreshCw } from 'lucide-react';
import { HeaderBar } from '../components/HeaderBar';
import { LoadingSkeleton } from '../components/LoadingSkeleton';
import { ErrorState } from '../components/ErrorState';
import { EmptyState } from '../components/EmptyState';
import { Pagination } from '../components/Pagination';
import { TokenDetailDrawer } from '../components/TokenDetailDrawer';
import { SignalFilters } from '../features/signals/SignalFilters';
import { SignalsTable } from '../features/signals/SignalsTable';
import { SignalsMobileList } from '../features/signals/SignalsMobileList';
import { fetchSignals } from '../lib/api';
import { POLL_INTERVAL_MS } from '../lib/constants';
import { queryKeys } from '../lib/queryKeys';

const DEFAULTS = { search: '', signal: null, sort: 'sentAt', order: 'desc', page: 1, limit: 20, token: null };
const SIGNALS = new Set(['BUY', 'WATCH']);
const SORTS = new Set(['sentAt', 'score']);
const ORDERS = new Set(['asc', 'desc']);
const LIMITS = new Set([10, 20, 50]);

export function SignalsPage() {
  const [searchParams, setSearchParams] = useSearchParams();
  const parsed = useMemo(() => parseParams(searchParams), [searchParams]);
  const [searchValue, setSearchValue] = useState(parsed.search);
  const returnFocusRef = useRef(null);

  useEffect(() => { setSearchValue(parsed.search); }, [parsed.search]);
  useEffect(() => {
    const canonical = new URLSearchParams();
    setParam(canonical, 'search', parsed.search, DEFAULTS.search);
    setParam(canonical, 'signal', parsed.signal, DEFAULTS.signal);
    setParam(canonical, 'sort', parsed.sort, DEFAULTS.sort);
    setParam(canonical, 'order', parsed.order, DEFAULTS.order);
    setParam(canonical, 'page', parsed.page, DEFAULTS.page);
    setParam(canonical, 'limit', parsed.limit, DEFAULTS.limit);
    setParam(canonical, 'token', parsed.token, DEFAULTS.token);
    if (canonical.toString() !== searchParams.toString()) setSearchParams(canonical, { replace: true });
  }, [parsed, searchParams, setSearchParams]);
  useEffect(() => {
    if (searchValue === parsed.search) return undefined;
    const timeout = window.setTimeout(() => updateParams({ search: searchValue.trim() || null, page: 1 }), 400);
    return () => window.clearTimeout(timeout);
  }, [searchValue, parsed.search]);

  const listFilters = useMemo(() => ({ search: parsed.search, signal: parsed.signal, sort: parsed.sort, order: parsed.order, page: parsed.page, limit: parsed.limit }), [parsed]);
  const signalsQuery = useQuery({
    queryKey: queryKeys.signals.list(listFilters),
    queryFn: ({ signal }) => fetchSignals(listFilters, { signal }),
    placeholderData: keepPreviousData,
    refetchInterval: POLL_INTERVAL_MS,
    staleTime: 10000,
    retry: (failureCount, error) => error?.status && error.status < 500 ? false : failureCount < 1,
    refetchIntervalInBackground: false
  });

  const rows = signalsQuery.data?.data || [];
  const pagination = signalsQuery.data?.pagination;
  const hasFilters = Boolean(parsed.search || parsed.signal);

  useEffect(() => { if (pagination?.totalPages && parsed.page > pagination.totalPages) updateParams({ page: pagination.totalPages }); }, [pagination?.totalPages, parsed.page]);

  function updateParams(updates) {
    setSearchParams((current) => {
      const next = new URLSearchParams(current);
      const merged = { ...parsed, ...updates };
      setParam(next, 'search', merged.search, DEFAULTS.search);
      setParam(next, 'signal', merged.signal, DEFAULTS.signal);
      setParam(next, 'sort', merged.sort, DEFAULTS.sort);
      setParam(next, 'order', merged.order, DEFAULTS.order);
      setParam(next, 'page', merged.page, DEFAULTS.page);
      setParam(next, 'limit', merged.limit, DEFAULTS.limit);
      setParam(next, 'token', merged.token, DEFAULTS.token);
      return next;
    });
  }
  function openDetail(address, element) { returnFocusRef.current = element; updateParams({ token: address }); }
  function closeDetail() { updateParams({ token: null }); }
  function resetFilters() { setSearchValue(''); updateParams({ search: null, signal: null, sort: DEFAULTS.sort, order: DEFAULTS.order, page: 1, limit: DEFAULTS.limit }); }

  const isInitialLoading = signalsQuery.isLoading && !signalsQuery.data;
  const isBackgroundError = signalsQuery.isError && Boolean(signalsQuery.data);
  return <>
    <HeaderBar title="Signal History" subtitle="BUY and WATCH signals generated by the scanner bot." />
    <div className="space-y-5 overflow-x-hidden">
      <SignalFilters filters={parsed} searchValue={searchValue} onSearchChange={setSearchValue} onChange={updateParams} onReset={resetFilters} disabled={signalsQuery.isFetching && !signalsQuery.data} />
      {signalsQuery.isFetching && signalsQuery.data && <div className="inline-flex items-center gap-2 rounded-full bg-blue-50 px-3 py-1 text-xs font-bold text-blue-700"><RefreshCw className="h-3 w-3 animate-spin" />Updating</div>}
      {isBackgroundError && <div className="rounded-2xl border border-amber-100 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">Could not refresh signals. Showing cached data.</div>}
      {isInitialLoading && <div role="status" aria-live="polite"><span className="sr-only">Loading signal history</span><LoadingSkeleton rows={4} /></div>}
      {signalsQuery.isError && !signalsQuery.data && <ErrorState title="Failed to load signals" message={signalsQuery.error?.message} onRetry={() => signalsQuery.refetch()} />}
      {!isInitialLoading && !signalsQuery.isError && rows.length === 0 && <EmptyWithReset hasFilters={hasFilters} onReset={resetFilters} />}
      {rows.length > 0 && <><SignalsTable rows={rows} onOpenDetail={openDetail} /><SignalsMobileList rows={rows} onOpenDetail={openDetail} /><Pagination pagination={pagination} onPageChange={(page) => updateParams({ page })} onLimitChange={(limit) => updateParams({ limit, page: 1 })} disabled={signalsQuery.isFetching && !signalsQuery.data} /></>}
    </div>
    {parsed.token && <TokenDetailDrawer address={parsed.token} onClose={closeDetail} returnFocusRef={returnFocusRef} />}
  </>;
}

function EmptyWithReset({ hasFilters, onReset }) { return <div className="space-y-3"><EmptyState title={hasFilters ? 'No signals match the current filters.' : 'No signal history is available yet.'} message={hasFilters ? 'Try resetting filters or searching another token.' : 'Signals generated by the bot will appear here.'} />{hasFilters && <div className="text-center"><button type="button" onClick={onReset} className="rounded-2xl bg-navy px-4 py-2 text-sm font-bold text-white">Reset Filters</button></div>}</div>; }
function parseParams(params) { const signal = normalizeEnum(params.get('signal'), SIGNALS); const sort = SORTS.has(params.get('sort')) ? params.get('sort') : DEFAULTS.sort; const order = ORDERS.has((params.get('order') || '').toLowerCase()) ? params.get('order').toLowerCase() : DEFAULTS.order; const limit = LIMITS.has(Number(params.get('limit'))) ? Number(params.get('limit')) : DEFAULTS.limit; const page = Math.max(1, Number.parseInt(params.get('page') || DEFAULTS.page, 10) || DEFAULTS.page); return { search: params.get('search') || '', signal, sort, order, page, limit, token: params.get('token') || null }; }
function normalizeEnum(value, allowed) { if (!value) return null; const normalized = value.toUpperCase(); return allowed.has(normalized) ? normalized : null; }
function setParam(params, key, value, defaultValue) { if (value === null || value === undefined || value === '' || value === defaultValue) params.delete(key); else params.set(key, String(value)); }
