import './main.css';
import { useEffect, useState } from 'react';
import { Area, AreaChart, CartesianGrid, Line, LineChart, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';
import { Activity, Bell, Bot, CircleHelp, Gauge, LayoutDashboard, LineChart as LineIcon, MessageSquare, Search, Settings, ShieldAlert, Sparkles, TrendingUp, Wallet, Zap } from 'lucide-react';
import { fetchDashboard } from './lib/api';

const fallback = { metrics: { portfolioValue: 0, pnlUsd: 0, pnlPercent: 0, activeCount: 0, maxHoldings: 5, riskIndex: 0, accuracy: 0 }, portfolio: [], signals: [], marketPulse: [], scoreHistory: [] };
const nav = [['Overview', LayoutDashboard], ['AI Chat', MessageSquare], ['Market', LineIcon], ['Portfolio', Wallet], ['Predictions', Sparkles], ['Exchanges', Activity], ['Community', Bot]];
const money = (v, d = 2) => { const n = Number(v || 0); return n >= 1000 ? `$${Math.round(n).toLocaleString('en-US')}` : `$${n.toLocaleString('en-US', { maximumFractionDigits: d })}`; };
const pct = (v) => `${Number(v || 0) >= 0 ? '+' : ''}${Number(v || 0).toFixed(2)}%`;
const signalClass = (s) => s === 'BUY' ? 'bg-emerald-100 text-emerald-700' : s === 'WATCH' ? 'bg-amber-100 text-amber-700' : 'bg-slate-100 text-slate-500';

function Sidebar() {
  return <aside className="fixed inset-y-0 left-0 hidden w-72 flex-col bg-navy px-5 py-6 text-white lg:flex">
    <div className="mb-10 flex items-center gap-3"><div className="grid h-11 w-11 place-items-center rounded-2xl bg-blue-500"><Zap /></div><div><div className="text-lg font-extrabold">KeyScanner coin</div><div className="text-xs text-blue-200">Solana meme radar</div></div></div>
    <nav className="space-y-2">{nav.map(([label, Icon], i) => <button key={label} className={`flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-left text-sm font-semibold ${i === 0 ? 'bg-white text-navy' : 'text-blue-100 hover:bg-white/10'}`}><Icon className="h-5 w-5" />{label}</button>)}</nav>
    <div className="mt-auto space-y-2 text-sm"><button className="flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-blue-100 hover:bg-white/10"><CircleHelp className="h-5 w-5" /> Help Center</button><button className="flex w-full items-center gap-3 rounded-2xl px-4 py-3 text-blue-100 hover:bg-white/10"><Settings className="h-5 w-5" /> Settings</button><div className="mt-5 rounded-3xl bg-white/10 p-4"><b>Scanner Status</b><p className="text-xs text-blue-100">Bot scans every 5 minutes</p><div className="mt-3 h-2 rounded-full bg-white/20"><div className="h-2 w-4/5 rounded-full bg-blue-400" /></div></div></div>
  </aside>;
}

function Header() {
  return <header className="mb-7 flex flex-col gap-4 md:flex-row md:items-center md:justify-between"><div><h1 className="text-3xl font-extrabold text-slate-950">Welcome back, Luthfi</h1><p className="text-sm text-slate-500">KeyScanner coin tracks Solana signals, portfolio risk, and AI scanner performance.</p></div><div className="flex items-center gap-3"><div className="hidden rounded-2xl bg-white px-4 py-3 shadow-card md:flex md:gap-2"><Search className="h-4 w-4 text-slate-400" /><span className="text-sm text-slate-400">Search token</span></div><button className="grid h-12 w-12 place-items-center rounded-2xl bg-white shadow-card"><Bell className="h-5 w-5" /></button><button className="rounded-2xl bg-blue-600 px-5 py-3 text-sm font-bold text-white">Upgrade</button></div></header>;
}

function PortfolioOverview({ data }) {
  const { metrics, portfolio } = data;
  const cards = portfolio.length ? portfolio.slice(0, 3) : [null, null, null];
  return <section className="rounded-[2rem] bg-white p-6 shadow-card"><div className="flex justify-between gap-4"><div><div className="text-sm font-semibold text-slate-500">Total Portfolio Value</div><div className="mt-2 text-4xl font-extrabold">{money(metrics.portfolioValue, 6)}</div><div className={`mt-2 text-sm font-bold ${metrics.pnlPercent >= 0 ? 'text-emerald-600' : 'text-red-500'}`}>{pct(metrics.pnlPercent)} / {money(metrics.pnlUsd, 6)} since entry</div></div><button className="h-fit rounded-2xl bg-navy px-5 py-3 text-sm font-bold text-white">Deposit</button></div><div className="mt-5 rounded-3xl bg-blue-50 p-4 text-sm text-slate-600"><b className="text-ocean">AI insight:</b> Active positions are monitored with TP, SL, and ATH drawdown alerts. Keep exposure capped while signals remain volatile.</div><div className="mt-5 grid gap-4 md:grid-cols-3">{cards.map((row, i) => <div key={row?.id || i} className="rounded-3xl border border-slate-100 bg-slate-50 p-4"><div className="flex items-center justify-between"><div className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-blue-600 font-bold text-white">{row?.symbol?.[0] || '?'}</div><div><b>{row?.symbol || 'No Position'}</b><div className="text-xs text-slate-500">Active token</div></div></div><span className={`text-sm font-bold ${Number(row?.pnl_percent || 0) >= 0 ? 'text-emerald-600' : 'text-red-500'}`}>{pct(row?.pnl_percent)}</span></div><div className="mt-4 text-xl font-extrabold">{money(row?.current_price || row?.entry_price || 0, 6)}</div><ResponsiveContainer width="100%" height={45}><AreaChart data={[10, 12, 9, 14, 13, 16].map((v, x) => ({ x, v: v + i }))}><Area dataKey="v" stroke="#2563EB" fill="#DBEAFE" strokeWidth={2} /></AreaChart></ResponsiveContainer></div>)}</div></section>;
}

function MarketPulse({ rows }) { return <section className="rounded-[2rem] bg-white p-5 shadow-card"><div className="mb-5 flex justify-between"><h2 className="text-lg font-extrabold">Market Pulse</h2><span className="text-xs font-semibold text-blue-600">Live</span></div><div className="space-y-4">{rows.slice(0, 7).map((r) => <div key={r.id} className="flex items-center gap-3"><div className="grid h-10 w-10 place-items-center rounded-2xl bg-blue-100 font-extrabold text-blue-700">{r.symbol?.[0] || '?'}</div><div className="min-w-0 flex-1"><div className="truncate text-sm font-bold">{r.symbol || 'UNKNOWN'}</div><div className="text-xs text-slate-400">Score {r.score}/100</div></div><div className="text-right"><div className="text-sm font-bold">{money(r.price_usd, 6)}</div><span className={`rounded-full px-2 py-1 text-[10px] font-bold ${signalClass(r.signal)}`}>{r.signal}</span></div></div>)}{!rows.length && <div className="text-sm text-slate-400">No scanned tokens yet.</div>}</div></section>; }

function ScoreHistory({ rows }) { const data = rows.length ? rows : Array.from({ length: 8 }, (_, i) => ({ label: `${i * 3}h`, avg_score: 0, max_score: 0 })); return <section className="rounded-[2rem] bg-white p-6 shadow-card"><div className="mb-5 flex justify-between"><div><h2 className="text-lg font-extrabold">AI Prediction Summary</h2><p className="text-sm text-slate-500">Token score history over the last 24 hours</p></div><div className="hidden gap-2 md:flex">{['1D', '7D', '1M', '3M', '6M', 'YTD'].map((x, i) => <button key={x} className={`rounded-xl px-3 py-2 text-xs font-bold ${i === 0 ? 'bg-blue-600 text-white' : 'bg-slate-100 text-slate-500'}`}>{x}</button>)}</div></div><ResponsiveContainer width="100%" height={290}><LineChart data={data}><CartesianGrid strokeDasharray="3 3" stroke="#E2E8F0" /><XAxis dataKey="label" stroke="#94A3B8" fontSize={12} /><YAxis stroke="#94A3B8" fontSize={12} domain={[0, 100]} /><Tooltip /><Line type="monotone" dataKey="avg_score" name="Avg Score" stroke="#2563EB" strokeWidth={3} dot={false} /><Line type="monotone" dataKey="max_score" name="Max Score" stroke="#0B1F3A" strokeWidth={3} dot={false} /></LineChart></ResponsiveContainer></section>; }

function StatCards({ metrics }) { return <div className="grid gap-5 lg:grid-cols-3"><div className="rounded-[2rem] bg-white p-6 shadow-card"><div className="flex gap-3 text-slate-500"><ShieldAlert /> Risk Index</div><div className="mt-4 text-3xl font-extrabold">{Math.round(metrics.riskIndex)}%</div><div className="mt-4 h-3 rounded-full bg-slate-100"><div className="h-3 rounded-full bg-gradient-to-r from-emerald-400 via-amber-400 to-red-500" style={{ width: `${Math.min(100, metrics.riskIndex)}%` }} /></div></div><div className="rounded-[2rem] bg-white p-6 shadow-card"><div className="flex gap-3 text-slate-500"><TrendingUp /> Portfolio P&L</div><div className={`mt-4 text-3xl font-extrabold ${metrics.pnlPercent >= 0 ? 'text-emerald-600' : 'text-red-500'}`}>{pct(metrics.pnlPercent)}</div><ResponsiveContainer width="100%" height={70}><AreaChart data={[1,3,2,5,4,6].map((v,i)=>({i,v}))}><Area dataKey="v" stroke="#22C55E" fill="#DCFCE7" /></AreaChart></ResponsiveContainer></div><div className="rounded-[2rem] bg-white p-6 shadow-card"><div className="flex gap-3 text-slate-500"><Gauge /> Confidence Score</div><div className="mt-4 text-3xl font-extrabold">{Math.round(metrics.accuracy)}%</div><div className="mt-4 grid grid-cols-10 gap-1">{Array.from({length:10},(_,i)=><div key={i} className={`h-8 rounded-lg ${i < Math.round(metrics.accuracy/10) ? 'bg-blue-600' : 'bg-slate-100'}`} />)}</div></div></div>; }

function SignalsPanel({ rows }) { return <section className="rounded-[2rem] bg-white p-5 shadow-card"><h2 className="mb-4 text-lg font-extrabold">Live BUY/WATCH Signals</h2><div className="space-y-3">{rows.slice(0,5).map((r)=><div key={r.id} className="rounded-2xl bg-slate-50 p-3"><div className="flex justify-between"><b>${r.symbol || r.token_address?.slice(0,4) || 'TOKEN'}</b><span className={`rounded-full px-2 py-1 text-xs font-bold ${signalClass(r.signal)}`}>{r.signal}</span></div><div className="mt-1 text-xs text-slate-500">Score {r.score}/100 • {new Date(r.sent_at).toLocaleString('id-ID')}</div></div>)}{!rows.length && <div className="text-sm text-slate-400">No alerts sent yet.</div>}</div></section>; }

export default function App() {
  const [data, setData] = useState(fallback);
  useEffect(() => { let ok = true; async function load(){ try { const res = await fetchDashboard(); if(ok) setData(res); } catch(e){ console.warn(e.message); } } load(); const t=setInterval(load,15000); return()=>{ok=false; clearInterval(t)}; }, []);
  return <div className="min-h-screen bg-soft"><Sidebar /><main className="lg:pl-72"><div className="mx-auto max-w-[1500px] px-5 py-6 md:px-8"><Header /><div className="mb-6 rounded-3xl bg-navy p-5 text-white shadow-card md:hidden"><div className="text-xl font-extrabold">KeyScanner coin</div><div className="text-sm text-blue-100">Dark blue scanner dashboard</div></div><div className="grid gap-6 xl:grid-cols-[1fr_360px]"><div className="space-y-6"><PortfolioOverview data={data} /><ScoreHistory rows={data.scoreHistory} /><StatCards metrics={data.metrics} /></div><div className="space-y-6"><MarketPulse rows={data.marketPulse} /><SignalsPanel rows={data.signals} /></div></div></div></main></div>;
}
