import React from 'react';
import { ExternalLink } from 'lucide-react';
import { formatPercent, formatUsd, formatWib, parseDecimal, shortAddress } from '../../lib/format';

export function ActivePositionsTable({ rows = [], onOpenDetail }) {
  return <div className="hidden overflow-x-auto rounded-[2rem] bg-white shadow-card lg:block"><table className="min-w-[1280px] w-full text-left text-sm">
    <thead className="bg-slate-50 text-xs uppercase tracking-wide text-slate-500"><tr><Th>Token</Th><Th>Entry Price</Th><Th>Current Price</Th><Th>Take Profit</Th><Th>Stop Loss</Th><Th>ATH Price</Th><Th>P&amp;L %</Th><Th>TP Progress</Th><Th>Distance to SL</Th><Th>Opened At</Th><Th>Status</Th></tr></thead>
    <tbody className="divide-y divide-slate-100">{rows.map((position) => <tr key={position.id} className="hover:bg-slate-50/80"><td className="px-5 py-4"><TokenCell position={position} onOpenDetail={onOpenDetail} /></td><td className="px-5 py-4">{formatUsd(position.entryPrice)}</td><td className="px-5 py-4">{formatUsd(position.currentPrice)}</td><td className="px-5 py-4"><div className="font-bold">{formatUsd(position.takeProfitPrice)}</div><div className="text-xs text-slate-400">{formatPercent(position.takeProfitPercent, { signed: false })}</div></td><td className="px-5 py-4">{formatUsd(position.stopLossPrice)}</td><td className="px-5 py-4">{formatUsd(position.athPrice)}</td><td className="px-5 py-4"><Pnl value={position.pnlPercent} /></td><td className="px-5 py-4"><TpProgress position={position} /></td><td className="px-5 py-4">{distanceToSl(position)}</td><td className="px-5 py-4 text-slate-600">{formatWib(position.openedAt, '—')}</td><td className="px-5 py-4"><span className="rounded-full bg-emerald-100 px-2.5 py-1 text-xs font-extrabold text-emerald-700">{position.status || '—'}</span></td></tr>)}</tbody>
  </table></div>;
}
function Th({ children }) { return <th scope="col" className="px-5 py-4 font-extrabold">{children}</th>; }
function TokenCell({ position, onOpenDetail }) { return <div className="min-w-[190px]"><div className="font-extrabold text-slate-950">{position.symbol || '—'}</div><div className="text-xs font-semibold text-slate-500">{shortAddress(position.tokenAddress)}</div><button type="button" onClick={(event) => onOpenDetail(position.tokenAddress, event.currentTarget)} className="mt-2 inline-flex items-center gap-1 rounded-xl bg-navy px-3 py-2 text-xs font-bold text-white focus:outline-none focus:ring-2 focus:ring-blue-400" aria-label={`View details for ${position.symbol || position.tokenAddress}`}>View <ExternalLink className="h-3 w-3" /></button></div>; }
function Pnl({ value }) { const number = parseDecimal(value); const color = number === null ? 'text-slate-500' : number > 0 ? 'text-emerald-700' : number < 0 ? 'text-red-700' : 'text-slate-700'; return <span className={`font-extrabold ${color}`}>{formatPercent(value)}</span>; }
export function computeTpProgress(position) { const entry = parseDecimal(position.entryPrice); const current = parseDecimal(position.currentPrice); const target = parseDecimal(position.takeProfitPrice); if (!entry || current === null || !target || target <= entry) return null; return ((current - entry) / (target - entry)) * 100; }
function TpProgress({ position }) { const progress = computeTpProgress(position); if (progress === null || !Number.isFinite(progress)) return '—'; const clamped = Math.max(0, Math.min(100, progress)); return <div className="min-w-[120px]"><div className="h-2 rounded-full bg-slate-100"><div className="h-2 rounded-full bg-emerald-500" style={{ width: `${clamped}%` }} /></div><div className="mt-1 text-xs font-bold text-slate-600">{progress >= 100 ? 'TP reached' : `${progress.toFixed(1)}%`}</div></div>; }
export function distanceToSl(position) { const current = parseDecimal(position.currentPrice); const stop = parseDecimal(position.stopLossPrice); if (!current || stop === null) return '—'; const value = ((current - stop) / current) * 100; return Number.isFinite(value) ? formatPercent(value, { signed: false }) : '—'; }
