import React from 'react';
import { formatPercent, formatUsd, formatWib, parseDecimal, shortAddress } from '../../lib/format';
import { distanceToSl } from './ActivePositionsTable';

export function PortfolioMobileList({ rows = [], status, onOpenDetail }) {
  return <div className="space-y-3 lg:hidden">{rows.map((position) => status === 'ACTIVE' ? <ActiveCard key={position.id} position={position} onOpenDetail={onOpenDetail} /> : <ClosedCard key={position.id} position={position} onOpenDetail={onOpenDetail} />)}</div>;
}
function ActiveCard({ position, onOpenDetail }) { return <article className="rounded-[2rem] bg-white p-4 shadow-card"><Header position={position} badge={position.status || 'ACTIVE'} /><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Item label="Entry" value={formatUsd(position.entryPrice)} /><Item label="Current" value={formatUsd(position.currentPrice)} /><Item label="P&L" value={<Pnl value={position.pnlPercent} />} /><Item label="TP" value={formatUsd(position.takeProfitPrice)} /><Item label="SL" value={formatUsd(position.stopLossPrice)} /><Item label="Distance to SL" value={distanceToSl(position)} /><Item label="Opened" value={formatWib(position.openedAt, '—')} wide /></div><DetailButton position={position} onOpenDetail={onOpenDetail} /></article>; }
function ClosedCard({ position, onOpenDetail }) { return <article className="rounded-[2rem] bg-white p-4 shadow-card"><Header position={position} badge="CLOSED" /><div className="mt-4 grid grid-cols-2 gap-3 text-sm"><Item label="P&L" value={<Pnl value={position.pnlPercent} />} /><Item label="Close reason" value={position.closeReason || '—'} /><Item label="Entry" value={formatUsd(position.entryPrice)} /><Item label="Close" value={formatUsd(position.closePrice)} /><Item label="Closed" value={formatWib(position.closedAt, '—')} wide /></div><DetailButton position={position} onOpenDetail={onOpenDetail} /></article>; }
function Header({ position, badge }) { return <div className="flex items-start justify-between gap-3"><div className="min-w-0"><div className="font-extrabold text-slate-950">{position.symbol || '—'}</div><div className="text-xs font-semibold text-slate-500">{shortAddress(position.tokenAddress)}</div></div><span className="rounded-full bg-slate-100 px-2.5 py-1 text-xs font-extrabold text-slate-700">{badge}</span></div>; }
function DetailButton({ position, onOpenDetail }) { return <button type="button" onClick={(event) => onOpenDetail(position.tokenAddress, event.currentTarget)} className="mt-4 w-full rounded-2xl bg-navy px-4 py-3 text-sm font-extrabold text-white focus:outline-none focus:ring-2 focus:ring-blue-400" aria-label={`View details for ${position.symbol || position.tokenAddress}`}>View details</button>; }
function Item({ label, value, wide }) { return <div className={wide ? 'col-span-2' : ''}><div className="text-xs font-bold uppercase text-slate-400">{label}</div><div className="font-bold text-slate-900">{value}</div></div>; }
function Pnl({ value }) { const number = parseDecimal(value); const color = number === null ? 'text-slate-500' : number > 0 ? 'text-emerald-700' : number < 0 ? 'text-red-700' : 'text-slate-700'; return <span className={color}>{formatPercent(value)}</span>; }
